version: "3"

services:
#  xray:
#    image: ghcr.io/xtls/xray-core:latest
#    container_name: XRay
#    restart: unless-stopped
#    volumes:
#      - ./data/v2ray/config.json:/usr/local/etc/xray/config.json:ro
#    ports:
#      - "443:443/tcp"
#    networks:
#      selfxray:

#  xui:
#    image: enwaiax/x-ui
#    container_name: xui
#    volumes:
#      - $PWD/db/:/etc/x-ui/
#      - $PWD/cert/:/root/cert/
#    restart: unless-stopped
#    network_mode: host

  3x-ui:
    image: metaligh/3x-ui:latest
    container_name: 3x-ui
    hostname: djkhgvkjsrvjks.duckdns.org
    volumes:
      - $PWD/db/:/etc/x-ui/
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped

#
#  ssl-proxy:
#    image: valian/docker-nginx-auto-ssl
#    restart: on-failure
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ssl_data:/etc/resty-auto-ssl
#    environment:
#      ALLOWED_DOMAINS: 'djkhgvkjsrvjks.duckdns.org'
#      SITES: 'djkhgvkjsrvjks.duckdns.org=site:80'
#
#  site:
#    image: nginx
#
#volumes:
#  ssl_data:
#
#networks:
#  selfxray:
#    driver:  bridge
#    enable_ipv6: false
#
